#!/usr/bin/env tclsh

package require Tclx

set servers_dir [file dirname $argv0]
source $servers_dir/tts-lib.tcl
load $servers_dir/linux-speechd/tclspeechd.so
tts_initialize


proc d {} {
    global tts

    loop index 0 [queue_length] {
        set event [queue_remove]
        set type [lindex $event 0]
        set content [lindex $event 1]

        switch $type {
            s {
                say $content
            }
            a {
                exec $tts(play) $content > /dev/null &
            }
        }
    }

    return ""
}


proc tts_say {text} {
    say $text
}


proc s {} {
    stop
    queue_clear
}


commandloop
